### ISSUE TITLE
Autofill Spinners doesn't work

### ISSUE THREAD

**Issue by aguillard** [googlesamples/android-AutofillFramework#12]
Hi,

I have tried your sample CreditCardSpinnersActivity and the Spinners isn't autofill, it works for the creditcardnumber and the vcc but spinners not moving. 

Tested on a Nexus 5X with Android 8.0.

**Comment by DougSig** [comment]
Hi sorry for such a late response. It works for me. 
1) Have you set the default autofill service to Multi-Dataset Autofill Service?
2) Have you tried filling in that page (instead of a different cc page) and saving the autofill data?

**Comment by aguillard** [comment]
Hi,

Question 1 : I tried with the "Autofill with Google" to get my credit card data saved on my google account.

Question 2 : To make a new test, I have changed my default autofill service to "Multi-Dataset Autofill Service" and fill a credit card form, but the system didn't ask my if I want to save my data....

**Comment by aguillard** [comment]
I have followed your instruction, and, in this case, it works !

So, my question still remain, why it works with the autofill provider "Multi-Dataset Autofill Service" but not with the provider "Autofill with Google" ?

**Comment by the-felipeal** [comment]
"Autofill with Google" does not support credit card expiration date like that yet, but it will soon. 

Anyways, the best way to test the sample apps (and your apps as well) is using the  "Multi-Dataset Autofill Service" implementation first. Think of the "Multi-Dataset Autofill Service" as a reference implementation - if your app works with it but not with other services, the problem is in the other service implementation, not in your app.

**Comment by aguillard** [comment]
Hi @the-felipeal !

You are right, it was a trouble in "Autofill with Google". I have changed nothing on my code and today it's working !
