### ISSUE TITLE
"Sample Credit Card Check Out Using Spinners" does not work.

### ISSUE THREAD

**Issue by ken5scal** [googlesamples/android-AutofillFramework#8]
When I fill user credentials in "Sample Login Using EditTexts" and "Sample Login Using AutoCompleteTextViews" for the first time,  I see the toast asking whether I want to save that information. 

![image](https://user-images.githubusercontent.com/9734362/27996090-40b84554-6515-11e7-9166-6bf6f150e267.png)

However, that toast had never appeared in our case when we use "Sample Credit Card Check Out Using Spinners". From my understanding, implementations of client app seem fine. I am using 5X on Android Emulator. Any clue?

**Comment by DougSig** [comment]
Hi! Does the save dialog come up when you modify every field on the page?

In the latest O developer preview, you need to modify every field on the page including Spinners. This will be fixed for the official O release, in that you will not need to select a spinner option in order to trigger autofill save dialog (since it has a default value).

**Comment by ken5scal** [comment]
It did after modifying all fields! Thanks so much!
